# Generated by Django 5.0.1 on 2024-02-14 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ims_category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ims_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('mobile', models.BigIntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ims_supplier',
            fields=[
                ('supplierid', models.AutoField(primary_key=True, serialize=False)),
                ('suppliername', models.CharField(max_length=200)),
                ('mobile', models.BigIntegerField()),
                ('address', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ims_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ims_category')),
            ],
        ),
        migrations.CreateModel(
            name='ims_product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('quantity', models.BigIntegerField()),
                ('unit', models.CharField(max_length=150)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateTimeField()),
                ('brandid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ims_brand')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ims_category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ims_supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ims_purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=255)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ims_product')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ims_supplier')),
            ],
        ),
    ]
