# Generated by Django 5.0.1 on 2024-02-14 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ims_order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_shiped', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('cutomer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ims_customer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ims_product')),
            ],
        ),
    ]
