# Generated by Django 5.0.1 on 2024-03-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ims_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ims_category',
            name='c_name',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
